# Generated by Django 5.1.7 on 2025-03-26 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("clientID", models.IntegerField(default=0)),
                (
                    "companyName",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("phone", models.CharField(blank=True, default="", max_length=128)),
                ("email", models.CharField(blank=True, default="", max_length=254)),
                (
                    "customerProfileID",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("isParent", models.BooleanField(default=False)),
                ("isChild", models.BooleanField(default=False)),
                ("parentClientID", models.IntegerField(default=0)),
                (
                    "defaultPaymentID",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                (
                    "salesperson",
                    models.CharField(blank=True, default="", max_length=128),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PaymentProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "processor",
                    models.CharField(
                        blank=True, default="AuthorizeNet", max_length=128
                    ),
                ),
                ("clientID", models.IntegerField(default=0)),
                ("createdBy", models.CharField(blank=True, default="", max_length=128)),
                (
                    "status",
                    models.CharField(blank=True, default="Active", max_length=128),
                ),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                (
                    "billedFrom",
                    models.CharField(
                        blank=True, default="Wholesale Communications", max_length=128
                    ),
                ),
                (
                    "customerProfileID",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                (
                    "paymentProfileID",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("firstName", models.CharField(blank=True, default="", max_length=128)),
                ("lastName", models.CharField(blank=True, default="", max_length=128)),
                ("email", models.CharField(blank=True, default="", max_length=254)),
                (
                    "streetAddress",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("state", models.CharField(blank=True, default="", max_length=128)),
                ("zipCode", models.CharField(blank=True, default="", max_length=128)),
                ("cardType", models.CharField(blank=True, default="", max_length=128)),
                ("lastFour", models.CharField(blank=True, default="", max_length=128)),
                ("isChildBillable", models.BooleanField(default=False)),
                (
                    "customerType",
                    models.CharField(blank=True, default="business", max_length=128),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("result", models.CharField(default="Not Submitted", max_length=64)),
                ("transID", models.CharField(blank=True, default="", max_length=254)),
                ("refID", models.CharField(max_length=64)),
                ("invoiceID", models.CharField(max_length=16)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("clientID", models.IntegerField(blank=True, default=0)),
                ("processor", models.CharField(blank=True, default="", max_length=128)),
                (
                    "billedFrom",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                (
                    "customerProfileID",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                (
                    "paymentProfileID",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("firstName", models.CharField(blank=True, default="", max_length=128)),
                ("lastName", models.CharField(blank=True, default="", max_length=128)),
                ("email", models.CharField(blank=True, default="", max_length=254)),
                (
                    "streetAddress",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("zipCode", models.CharField(blank=True, default="", max_length=128)),
                ("isParentBilled", models.BooleanField(default=False)),
                ("amount", models.CharField(max_length=64)),
                ("salesperson", models.CharField(max_length=254)),
                ("submitted", models.BooleanField(default=False)),
                (
                    "resultStatus",
                    models.CharField(blank=True, default="", max_length=8),
                ),
                ("resultCode", models.CharField(blank=True, default="", max_length=16)),
                (
                    "resultNumber",
                    models.CharField(blank=True, default="", max_length=16),
                ),
                (
                    "resultText",
                    models.CharField(blank=True, default="", max_length=254),
                ),
                (
                    "responseCode",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                ("authCode", models.CharField(blank=True, default="", max_length=6)),
                (
                    "avsResultCode",
                    models.CharField(blank=True, default="", max_length=254),
                ),
                (
                    "cvvResultCode",
                    models.CharField(blank=True, default="", max_length=254),
                ),
                (
                    "cavvResultCode",
                    models.CharField(blank=True, default="", max_length=254),
                ),
                (
                    "networkTransId",
                    models.CharField(blank=True, default="", max_length=254),
                ),
                (
                    "accountNumber",
                    models.CharField(blank=True, default="", max_length=254),
                ),
                (
                    "accountType",
                    models.CharField(blank=True, default="", max_length=254),
                ),
                ("error", models.CharField(blank=True, default="", max_length=254)),
                ("errorText", models.CharField(blank=True, default="", max_length=254)),
            ],
        ),
    ]
