# Generated by Django 5.1.7 on 2025-03-27 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("PayPortal", "0002_clientnotes"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ClientNotes",
            new_name="ClientNote",
        ),
    ]
