# Generated by Django 5.1.7 on 2025-04-03 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PayPortal", "0003_rename_clientnotes_clientnote"),
    ]

    operations = [
        migrations.RenameField(
            model_name="client",
            old_name="customerProfileID",
            new_name="wcCustomerProfileID",
        ),
        migrations.AddField(
            model_name="client",
            name="cgCustomerProfileID",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="client",
            name="vbcCustomerProfileID",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="clientnote",
            name="special",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="processor",
            field=models.CharField(blank=True, default="AuthorizeNet", max_length=128),
        ),
    ]
