# Generated by Django 5.1.7 on 2025-03-24 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PaymentProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("createdBy", models.CharField(default="", max_length=128)),
                ("clientID", models.IntegerField(default=0)),
                (
                    "companyName",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("firstName", models.CharField(blank=True, default="", max_length=128)),
                ("lastName", models.CharField(blank=True, default="", max_length=128)),
                ("address", models.CharField(blank=True, default="", max_length=128)),
                ("zipCode", models.CharField(blank=True, default="", max_length=128)),
                ("customerType", models.CharField(default="business", max_length=32)),
                (
                    "customerProfileID",
                    models.CharField(blank=True, default="", max_length=12),
                ),
                (
                    "paymentProfileID",
                    models.CharField(blank=True, default="", max_length=16),
                ),
                ("status", models.CharField(default="Active", max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("result", models.CharField(default="Not Submitted", max_length=64)),
                ("clientID", models.IntegerField(blank=True, default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("invoiceID", models.CharField(max_length=16)),
                ("transID", models.CharField(blank=True, default="", max_length=254)),
                ("refID", models.CharField(max_length=64)),
                ("amount", models.CharField(max_length=64)),
                ("salesperson", models.CharField(max_length=254)),
                ("submitted", models.BooleanField(default=False)),
                (
                    "resultStatus",
                    models.CharField(blank=True, default="", max_length=8),
                ),
                ("resultCode", models.CharField(blank=True, default="", max_length=16)),
                (
                    "resultNumber",
                    models.CharField(blank=True, default="", max_length=16),
                ),
                (
                    "resultText",
                    models.CharField(blank=True, default="", max_length=254),
                ),
                (
                    "responseCode",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                ("authCode", models.CharField(blank=True, default="", max_length=6)),
                (
                    "avsResultCode",
                    models.CharField(blank=True, default="", max_length=254),
                ),
                (
                    "cvvResultCode",
                    models.CharField(blank=True, default="", max_length=254),
                ),
                (
                    "cavvResultCode",
                    models.CharField(blank=True, default="", max_length=254),
                ),
                (
                    "networkTransId",
                    models.CharField(blank=True, default="", max_length=254),
                ),
                (
                    "accountNumber",
                    models.CharField(blank=True, default="", max_length=254),
                ),
                (
                    "accountType",
                    models.CharField(blank=True, default="", max_length=254),
                ),
                ("error", models.CharField(blank=True, default="", max_length=254)),
                ("errorText", models.CharField(blank=True, default="", max_length=254)),
            ],
        ),
    ]
