# Generated by Django 5.1.7 on 2025-03-18 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("invoiceID", models.CharField(max_length=16)),
                ("refID", models.CharField(max_length=64)),
                ("amount", models.CharField(max_length=64)),
                ("salesperson", models.CharField(max_length=254)),
                ("submitted", models.BooleanField(default=False)),
                ("transId", models.CharField(blank=True, max_length=254, null=True)),
                ("responseCode", models.IntegerField(blank=True, null=True)),
                ("apiCode", models.CharField(blank=True, max_length=32, null=True)),
                ("authCode", models.CharField(blank=True, max_length=6, null=True)),
                (
                    "accountNumber",
                    models.CharField(blank=True, max_length=254, null=True),
                ),
                (
                    "accountType",
                    models.CharField(blank=True, max_length=254, null=True),
                ),
                ("error", models.CharField(blank=True, max_length=254, null=True)),
                ("errorText", models.CharField(blank=True, max_length=254, null=True)),
            ],
        ),
    ]
