# Generated by Django 5.1.7 on 2025-03-24 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("result", models.CharField(default="Not Submitted", max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("invoiceID", models.CharField(max_length=16)),
                ("transId", models.CharField(blank=True, max_length=254, null=True)),
                ("refID", models.CharField(max_length=64)),
                ("amount", models.CharField(max_length=64)),
                ("salesperson", models.CharField(max_length=254)),
                ("submitted", models.BooleanField(default=False)),
                ("resultStatus", models.CharField(blank=True, max_length=8, null=True)),
                ("resultCode", models.CharField(blank=True, max_length=16, null=True)),
                (
                    "resultNumber",
                    models.CharField(blank=True, max_length=16, null=True),
                ),
                ("resultText", models.CharField(blank=True, max_length=254, null=True)),
                (
                    "responseCode",
                    models.CharField(blank=True, max_length=32, null=True),
                ),
                ("authCode", models.CharField(blank=True, max_length=6, null=True)),
                (
                    "avsResultCode",
                    models.CharField(blank=True, max_length=254, null=True),
                ),
                (
                    "cvvResultCode",
                    models.CharField(blank=True, max_length=254, null=True),
                ),
                (
                    "cavvResultCode",
                    models.CharField(blank=True, max_length=254, null=True),
                ),
                (
                    "networkTransId",
                    models.CharField(blank=True, max_length=254, null=True),
                ),
                (
                    "accountNumber",
                    models.CharField(blank=True, max_length=254, null=True),
                ),
                (
                    "accountType",
                    models.CharField(blank=True, max_length=254, null=True),
                ),
                ("error", models.CharField(blank=True, max_length=254, null=True)),
                ("errorText", models.CharField(blank=True, max_length=254, null=True)),
            ],
        ),
    ]
