# Generated by Django 5.1.7 on 2025-03-24 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentprofile",
            name="email",
            field=models.CharField(blank=True, default="", max_length=254),
        ),
    ]
