# Generated by Django 5.1.7 on 2025-03-24 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.CharField(max_length=128)),
                ("clientID", models.IntegerField(null=True)),
                ("companyName", models.CharField(max_length=128, null=True)),
                ("firstName", models.CharField(max_length=128, null=True)),
                ("lastName", models.CharField(max_length=128, null=True)),
                ("address", models.CharField(max_length=128, null=True)),
                ("zipCode", models.CharField(max_length=128, null=True)),
                ("email", models.CharField(max_length=32, null=True)),
                (
                    "customerType",
                    models.CharField(default="Business", max_length=32, null=True),
                ),
                ("customerProfileID", models.CharField(max_length=12, null=True)),
                ("paymentProfileID", models.CharField(max_length=16, null=True)),
                (
                    "status",
                    models.CharField(default="Active", max_length=32, null=True),
                ),
            ],
        ),
    ]
