# Generated by Django 5.1.7 on 2025-03-18 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="apiCode",
        ),
        migrations.AddField(
            model_name="transaction",
            name="avsResultCode",
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="cavvResultCode",
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="cvvResultCode",
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="networkTransId",
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="result",
            field=models.CharField(default="Not Submitted", max_length=64),
        ),
        migrations.AddField(
            model_name="transaction",
            name="resultCode",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="resultStatus",
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="resultText",
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="responseCode",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
