# Generated by Django 5.1.7 on 2025-03-18 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "portal",
            "0002_remove_transaction_apicode_transaction_avsresultcode_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="resultNumber",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="resultCode",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
